# NOTE: We're currently not running build tasks inside docker containers because of
# bad performance and missing docker caching in gitlab. See these issues for example:
# - https://gitlab.com/gitlab-org/gitlab-ce/issues/17861#note_37212331
# - https://gitlab.com/gitlab-org/gitlab-ce/issues/33313

cache:
  untracked: true
  key: $CI_COMMIT_REF_NAME
  paths:
    - .yarn-cache/

variables:
  # From the docs: https://docs.gitlab.com/ee/ci/yaml/#git-strategy
  #   „fetch is faster as it re-uses the project workspace (falling back
  #   to clone if it doesn't exist). git clean is used to undo any changes
  #   made by the last job, and git fetch is used to retrieve commits
  #   made since the last job ran.“
  GIT_STRATEGY: fetch

  # https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
  # The 'latest' image. Used as a base to cache from
  # when building the $BUILD_IMAGE.
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
        #  - setup
        #  - test
        #  - build
  - deploy
  - stop-review

before_script:
  # The image generated in this build
  - eval export SANITIZED_BRANCH_NAME=$(echo $CI_COMMIT_REF_NAME | sed -e "s/\//-/g")
  - eval export BUILD_IMAGE=$CI_REGISTRY_IMAGE:$SANITIZED_BRANCH_NAME
  # The fqdn of the gitlab server is not available in the standard env vars so we cut it out of this URL
  - eval export GITLAB_HOSTNAME=$(echo $CI_PROJECT_URL | awk -F/ '{print $3}')

setup:
  stage: setup
  artifacts:
    expire_in: 3d
    paths:
      - node_modules
  script:
    - eval `ssh-agent -s`
    - ssh-add <(echo "$GITLAB_BOT_SSH_KEY")
    - yarn install --pure-lockfile --cache-folder .yarn-cache


build-and-push-docker-image:
  stage: build
  # This is OR logic. The commit should be in master OR be tagged
  cache:
    policy: pull
  script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    # Using `--pull` makes sure that Docker fetches any changes to the $RELEASE_IMAGE before building
    # just in case our cache is stale. It takes slightly longer, but means we don’t get stuck without
    # potential security patches to base images.
    #
    # Using `--cache-from $RELEASE_IMAGE` can speed  up building the $BUILD_IMAGE
    # https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
    - docker build --pull --cache-from $RELEASE_IMAGE --tag $BUILD_IMAGE --build-arg GITLAB_BOT_SSH_KEY="$GITLAB_BOT_SSH_KEY" .
    - docker push $BUILD_IMAGE

    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE


deploy-review:
  stage: deploy
  environment:
    name: rev-claim-brk--$CI_BUILD_REF_NAME
    url: https://rev-claim-brk--$CI_COMMIT_REF_SLUG.brickblock-cloud.io
    on_stop: stop-review
  only:
    - branches
  except:
    - master
#  variables:
#    GIT_STRATEGY: none
  tags:
    - google
#    - review-apps
#    - deploy
  script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - env
    - pwd
    - /bin/bash $(pwd)/k8s/deploy.sh rev-platform--$CI_COMMIT_REF_SLUG
      #    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOSTNAME}/andrew.holway/deploy-scripts.git
      #    - /bin/sh $(pwd)/deploy-scripts/deploy.sh map-api

stop-review:
  stage: stop-review
  environment:
    name: rev-claim-brk--$CI_BUILD_REF_NAME
    url: https://rev-claim-brk--$CI_COMMIT_REF_SLUG.brickblock-cloud.io
    action: stop
  when: manual
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOSTNAME}/andrew.holway/deploy-scripts.git
    - /bin/sh $(pwd)/deploy-scripts/destroy.sh map-api
  only:
    - branches
  except:
    - master

deploy-staging:
  stage: deploy
  environment:
    name: staging-claim-brk
    url: https://staging-claim-brk.brickblock-cloud.io
  only:
    - master
  script:
    - python --version
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOSTNAME}/andrew.holway/deploy-scripts.git
    - /bin/sh $(pwd)/deploy-scripts/deploy.sh address-map-api

deploy-production:
  stage: deploy
  environment:
    name: production-claim-brk
    url: https://production-claim-brk.brickblock-cloud.io
  script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOSTNAME}/andrew.holway/deploy-scripts.git
    - /bin/sh $(pwd)/deploy-scripts/deploy.sh address-map-api
  # These two 'onlys' give us AND logic. The commit should both be in master AND be tagged. NB. this is git tagging. not 'gitlab' tagging.
  only:
    - master
  only:
    - tags

