# To run this locally, you must have started the DB (`$ docker-compose up`) and the app (`$ yarn start`)
GET http://localhost:8080/
# This file is written in a format that the "restclient-mode" program can run. It's written in Emacs lisp, so pretty shitty stuff. Should not be hard to make a shell script that calls curl based on this data though. Easy to parse

POST http://localhost:8080/address-map
{
  "address": "1Au9ATfh7btcE2ongcYs7HdmFP3X87By5x",
  "ethereumAddress": "0x908ad7535af813aa60fdfce13bfc203ae5f3fcfe",
  "signature": "IEIpDoCrsQqGZrdZNflrEk8vuDI8TzgwOAIPRdJtsdg8fFkt+SgV4uMG5zI95REQebg1hiz/7m+zo6DfHdyceWA="
}
